//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSValueTransformer.h"

@interface BackgroundStyle2RemoveButton : NSValueTransformer
{
}

+ (BOOL)allowsReverseTransformation;	// IMP=0x000000000001862b
+ (Class)transformedValueClass;	// IMP=0x000000000001860f
- (id)transformedValue:(id)arg1;	// IMP=0x0000000000018633

@end

