//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSValueTransformer.h"

@interface BackgroundStyle2AlternateRemoveButton : NSValueTransformer
{
}

+ (BOOL)allowsReverseTransformation;	// IMP=0x000000000001880d
+ (Class)transformedValueClass;	// IMP=0x00000000000187f1
- (id)transformedValue:(id)arg1;	// IMP=0x0000000000018815

@end

