//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSImage, NSNumber, NSTableCellView, NSTextField;

@interface BT_BatteryControl : NSView
{
    int batteryState;	// 152 = 0x98
    BOOL scalesWhenResized;	// 156 = 0x9c
    float floatValue;	// 160 = 0xa0
    float redLevelThreshold;	// 164 = 0xa4
    float receivedValue;	// 168 = 0xa8
    NSImage *batteryImage;	// 176 = 0xb0
    NSImage *levelImage0;	// 184 = 0xb8
    NSImage *levelImage1;	// 192 = 0xc0
    NSImage *levelImage2;	// 200 = 0xc8
    BOOL isUsingRedLevel;	// 208 = 0xd0
    BOOL mSelected;	// 209 = 0xd1
    BOOL mDrawNow;	// 210 = 0xd2
    NSNumber *floatVal;	// 216 = 0xd8
    NSTextField *mDeviceName;	// 224 = 0xe0
    NSTableCellView *mBT_Row;	// 232 = 0xe8
}

+ (id)_batteryLevelImage:(unsigned char)arg1 useRedVersion:(BOOL)arg2;	// IMP=0x0000000000002350
+ (id)_batteryImageForState:(int)arg1;	// IMP=0x00000000000022a4
+ (id)_batteryImageWithName:(id)arg1;	// IMP=0x0000000000002211
@property NSTableCellView *BT_row; // @synthesize BT_row=mBT_Row;
@property NSTextField *BT_deviceName; // @synthesize BT_deviceName=mDeviceName;
@property(nonatomic) float redLevelThreshold; // @synthesize redLevelThreshold;
@property(nonatomic) float floatValue; // @synthesize floatValue;
@property(nonatomic) int batteryState; // @synthesize batteryState;
@property(nonatomic) BOOL scalesWhenResized; // @synthesize scalesWhenResized;
- (float)batteryPercentForIcon;	// IMP=0x0000000000002f06
- (void)drawRect:(struct CGRect)arg1;	// IMP=0x0000000000002c7c
- (void)_drawBatteryLevelWithRect:(struct CGRect)arg1 batteryImageRect:(struct CGRect)arg2;	// IMP=0x0000000000002a9f
- (void)_drawBatteryImage:(id)arg1 withRect:(struct CGRect)arg2 inRect:(struct CGRect *)arg3;	// IMP=0x0000000000002833
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00000000000026c2
- (void)_setupLevelImages;	// IMP=0x00000000000025e3
- (void)receivedRowSelected:(id)arg1;	// IMP=0x00000000000025cc
- (void)dealloc;	// IMP=0x00000000000024df
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00000000000023b2

@end

