//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSValueTransformer.h"

@interface Connected2ImageIndicatorTransformer : NSValueTransformer
{
}

+ (BOOL)allowsReverseTransformation;	// IMP=0x0000000000018a6f
+ (Class)transformedValueClass;	// IMP=0x0000000000018a53
- (id)transformedValue:(id)arg1;	// IMP=0x0000000000018a77

@end

