//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IOBluetoothDeviceInquiry.h"

#import "D2DInquiry.h"

@class NSArray, NSMutableDictionary;

@interface D2DBluetoothDeviceInquiry : IOBluetoothDeviceInquiry <D2DInquiry>
{
    int mInquiryClass;	// 112 = 0x70
    int mInquirySubclass;	// 116 = 0x74
    NSMutableDictionary *mInquiryDelegates;	// 120 = 0x78
    struct IOBluetoothDeviceSearchAttributes *mSearchAttributes;	// 128 = 0x80
}

+ (id)inquiryWithDeviceClass:(int)arg1;	// IMP=0x00000000000073ee
@property struct IOBluetoothDeviceSearchAttributes *inquirySearchAttributes; // @synthesize inquirySearchAttributes=mSearchAttributes;
@property int inquirySubclass; // @synthesize inquirySubclass=mInquirySubclass;
@property int inquiryClass; // @synthesize inquiryClass=mInquiryClass;
- (void)deviceInquiryComplete:(id)arg1 error:(int)arg2 aborted:(BOOL)arg3;	// IMP=0x00000000000076f4
- (void)deviceInquiryDeviceNameUpdated:(id)arg1 device:(id)arg2 devicesRemaining:(unsigned int)arg3;	// IMP=0x0000000000007679
- (void)deviceInquiryUpdatingDeviceNamesStarted:(id)arg1 devicesRemaining:(unsigned int)arg2;	// IMP=0x0000000000007673
- (void)deviceInquiryDeviceFound:(id)arg1 device:(id)arg2;	// IMP=0x000000000000759c
- (void)deviceInquiryStarted:(id)arg1;	// IMP=0x00000000000074f4
- (BOOL)resetInquiry:(id *)arg1;	// IMP=0x00000000000074c2
- (BOOL)stopInquiry:(id *)arg1;	// IMP=0x00000000000074aa
- (BOOL)startInquiry:(id *)arg1;	// IMP=0x0000000000007409
@property(readonly) NSArray *foundDevices;
@property id inquiryDelegate;
@property BOOL inquiryUpdatesDeviceNames;
@property double inquiryInterval;

@end

