//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface D2DDiscovery : NSObject
{
    id delegate;	// 8 = 0x8
    id <D2DPeer> device;	// 16 = 0x10
}

+ (id)discoveryForDevice:(id)arg1;	// IMP=0x0000000000018c0d
@property(retain) id <D2DPeer> device; // @synthesize device;
@property id delegate; // @synthesize delegate;
- (BOOL)stopDiscovery:(id *)arg1;	// IMP=0x0000000000018c6b
- (BOOL)startDiscovery:(id *)arg1;	// IMP=0x0000000000018c63

@end

