//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "D2DInquiry.h"

@class NSArray, NSMutableArray, NSMutableSet;

@interface D2DInquiry : NSObject <D2DInquiry>
{
    int inquiryClass;	// 8 = 0x8
    int inquirySubclass;	// 12 = 0xc
    struct IOBluetoothDeviceSearchAttributes *inquirySearchAttributes;	// 16 = 0x10
    double inquiryInterval;	// 24 = 0x18
    BOOL inquiryUpdatesDeviceNames;	// 32 = 0x20
    id inquiryDelegate;	// 40 = 0x28
    NSMutableArray *foundDevices;	// 48 = 0x30
    NSMutableSet *protocolInquries;	// 56 = 0x38
}

+ (id)inquiryWithAttribute:(struct IOBluetoothDeviceSearchAttributes *)arg1;	// IMP=0x00000000000035e8
+ (id)inquiryWithDeviceClass:(int)arg1;	// IMP=0x00000000000035a1
@property(readonly) NSArray *foundDevices; // @synthesize foundDevices;
@property id inquiryDelegate; // @synthesize inquiryDelegate;
@property BOOL inquiryUpdatesDeviceNames; // @synthesize inquiryUpdatesDeviceNames;
@property double inquiryInterval; // @synthesize inquiryInterval;
@property struct IOBluetoothDeviceSearchAttributes *inquirySearchAttributes; // @synthesize inquirySearchAttributes;
@property int inquirySubclass; // @synthesize inquirySubclass;
@property int inquiryClass; // @synthesize inquiryClass;
- (void)inquiryComplete:(id)arg1 error:(id)arg2;	// IMP=0x0000000000004036
- (void)inquiry:(id)arg1 deviceNameUpdated:(id)arg2 devicesRemaining:(unsigned long long)arg3;	// IMP=0x0000000000003f3a
- (void)inquiry:(id)arg1 startedUpdatingDeviceNames:(unsigned long long)arg2;	// IMP=0x0000000000003ec2
- (void)inquiry:(id)arg1 updatedDevice:(id)arg2;	// IMP=0x0000000000003de7
- (void)inquiry:(id)arg1 foundDevice:(id)arg2;	// IMP=0x0000000000003cda
- (void)inquiryStarted:(id)arg1;	// IMP=0x0000000000003c77
- (BOOL)resetInquiry:(id *)arg1;	// IMP=0x0000000000003b7c
- (BOOL)stopInquiry:(id *)arg1;	// IMP=0x0000000000003a81
- (BOOL)startInquiry:(id *)arg1;	// IMP=0x000000000000382f
- (void)dealloc;	// IMP=0x00000000000037e5
- (id)initWithAttribute:(struct IOBluetoothDeviceSearchAttributes *)arg1;	// IMP=0x000000000000370b
- (id)initWithDeviceClass:(int)arg1;	// IMP=0x0000000000003631

@end

