//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSImage, NSString;

@interface D2DPersonality : NSObject
{
    NSDictionary *personality;	// 8 = 0x8
}

+ (id)personalityForDevice:(id)arg1;	// IMP=0x0000000000016364
+ (id)personalityForIdentifier:(id)arg1;	// IMP=0x0000000000016205
@property(readonly) NSString *deviceSubtypeName;
@property(readonly) NSString *deviceTypeName;
@property(readonly) NSString *deviceModelName;
@property(readonly) NSString *deviceMakeName;
@property(readonly) NSImage *deviceImage;
@property(readonly) NSString *identifier;
- (void)dealloc;	// IMP=0x00000000000167bb
- (id)initWithDictionary:(id)arg1;	// IMP=0x0000000000016758

@end

