//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "D2DProtocol.h"

@class NSMutableDictionary;

@interface D2DProtocolManager : NSObject <D2DProtocol>
{
    id delegate;	// 8 = 0x8
    NSMutableDictionary *protocols;	// 16 = 0x10
}

+ (void)postProtocolNotification:(id)arg1 forProtocol:(id)arg2 withObject:(id)arg3;	// IMP=0x00000000000041da
+ (id)systemDeviceManager;	// IMP=0x000000000000419e
@property id delegate; // @synthesize delegate;
- (id)registeredProtocolNames;	// IMP=0x000000000000486e
- (void)unregisterProtocolManager:(id)arg1;	// IMP=0x0000000000004851
- (id)registeredProtocolManager:(id)arg1;	// IMP=0x0000000000004831
- (void)registerProtocolManager:(id)arg1;	// IMP=0x00000000000047e4
- (BOOL)unpairWithDevice:(id)arg1;	// IMP=0x0000000000004777
- (id)pairWithDevice:(id)arg1;	// IMP=0x000000000000470a
- (id)searchForDevicesWithAttribute:(struct IOBluetoothDeviceSearchAttributes *)arg1;	// IMP=0x000000000000468c
- (id)searchForDevicesOfType:(int)arg1;	// IMP=0x000000000000460e
- (id)connectedDevices;	// IMP=0x00000000000044d6
- (id)pairedDevices;	// IMP=0x000000000000439e
- (BOOL)bluetoothPowerOff;	// IMP=0x00000000000042ff
- (id)protocolName;	// IMP=0x00000000000042f2
- (void)dealloc;	// IMP=0x00000000000042a8
- (id)init;	// IMP=0x0000000000004248

@end

