//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "D2DInquiryDelegate.h"

@class NSImageView, NSMatrix, NSTabView, NSTextField;

@interface D2DPairingView : NSViewController <D2DInquiryDelegate>
{
    id <D2DInquiry> mInquiry;	// 104 = 0x68
    BOOL mActive;	// 112 = 0x70
    NSTabView *pairingTabs;	// 120 = 0x78
    NSImageView *automaticIndicator;	// 128 = 0x80
    NSMatrix *passcodeMatrix;	// 136 = 0x88
    NSTextField *passcodeField;	// 144 = 0x90
    NSTextField *comparisonCode;	// 152 = 0x98
    id <D2DPeer> device;	// 160 = 0xa0
    id <D2DPairing> pairing;	// 168 = 0xa8
}

+ (id)pairingViewForDevice:(id)arg1;	// IMP=0x0000000000015c2b
+ (id)searchViewForDevicesOfClass:(int)arg1 subclass:(int)arg2;	// IMP=0x0000000000015b69
@property BOOL active; // @synthesize active=mActive;
@property(retain) id <D2DInquiry> inquiry; // @synthesize inquiry=mInquiry;
@property(retain) id <D2DPeer> device; // @synthesize device;
- (void)inquiryComplete:(id)arg1 error:(id)arg2;	// IMP=0x0000000000015f6b
- (void)inquiry:(id)arg1 deviceNameUpdated:(id)arg2 devicesRemaining:(unsigned long long)arg3;	// IMP=0x0000000000015f39
- (void)inquiry:(id)arg1 updatedDevice:(id)arg2;	// IMP=0x0000000000015f07
- (void)inquiry:(id)arg1 foundDevice:(id)arg2;	// IMP=0x0000000000015ed5
- (void)inquiryStarted:(id)arg1;	// IMP=0x0000000000015e58
- (void)devicePairingUserPasskeyNotification:(id)arg1 passkey:(unsigned long long)arg2;	// IMP=0x0000000000015e39
- (void)devicePairingUserConfirmationRequest:(id)arg1 numericValue:(unsigned long long)arg2;	// IMP=0x0000000000015e17
- (void)devicePairingPINCodeRequest:(id)arg1;	// IMP=0x0000000000015df5
- (void)cancelSearch:(id)arg1;	// IMP=0x0000000000015db5
- (void)startSearch:(id)arg1;	// IMP=0x0000000000015d75
- (void)cancelPairing;	// IMP=0x0000000000015d58
- (void)startPairing;	// IMP=0x0000000000015cb9

@end

