//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "D2DPeer.h"

@class D2DPersonality, NSData, NSDictionary, NSString, NSURL;

@interface D2DPeer : NSObject <D2DPeer>
{
    NSString *deviceName;	// 8 = 0x8
    NSData *deviceAddress;	// 16 = 0x10
    NSURL *deviceURL;	// 24 = 0x18
    int deviceClass;	// 32 = 0x20
    int deviceSubclass;	// 36 = 0x24
    NSString *nickName;	// 40 = 0x28
    NSDictionary *devicePreferences;	// 48 = 0x30
    NSDictionary *deviceProperties;	// 56 = 0x38
    BOOL connected;	// 64 = 0x40
    BOOL paired;	// 65 = 0x41
    BOOL isConnectable;	// 66 = 0x42
    float batteryPercent;	// 68 = 0x44
    BOOL hasPairingOptions;	// 72 = 0x48
    BOOL hasResolvedName;	// 73 = 0x49
    int sortingOrder;	// 76 = 0x4c
    id deviceDelegate;	// 80 = 0x50
    BOOL foundRSSI;	// 88 = 0x58
    unsigned int servicesConfigured;	// 92 = 0x5c
}

+ (id)protocolName;	// IMP=0x00000000000032df
@property(readonly) unsigned int servicesConfigured; // @synthesize servicesConfigured;
@property(readonly) BOOL foundRSSI; // @synthesize foundRSSI;
@property(readonly) int sortingOrder; // @synthesize sortingOrder;
@property(readonly) BOOL hasResolvedName; // @synthesize hasResolvedName;
@property(readonly) BOOL hasPairingOptions; // @synthesize hasPairingOptions;
@property(readonly) float batteryPercent; // @synthesize batteryPercent;
@property(readonly) BOOL isConnectable; // @synthesize isConnectable;
@property(readonly) BOOL paired; // @synthesize paired;
@property(readonly) BOOL connected; // @synthesize connected;
@property id deviceDelegate; // @synthesize deviceDelegate;
@property(readonly) NSDictionary *deviceProperties; // @synthesize deviceProperties;
@property(readonly) NSDictionary *devicePreferences; // @synthesize devicePreferences;
@property(readonly) int deviceSubclass; // @synthesize deviceSubclass;
@property(readonly) int deviceClass; // @synthesize deviceClass;
@property(readonly) NSURL *deviceURL; // @synthesize deviceURL;
@property(readonly) NSData *deviceAddress; // @synthesize deviceAddress;
@property(copy) NSString *deviceName; // @synthesize deviceName;
- (BOOL)isTrackpad;	// IMP=0x0000000000003428
- (int)maxNameLength;	// IMP=0x0000000000003403
- (id)deviceServices;	// IMP=0x00000000000033ea
- (id)deviceBehaviours;	// IMP=0x0000000000003360
- (id)deviceIcon;	// IMP=0x0000000000003332
- (void)disconnectDevice;	// IMP=0x000000000000331f
- (void)connectDevice;	// IMP=0x000000000000330c
@property(readonly) D2DPersonality *personality;

@end

