//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface D2DSpectrumManager : NSObject
{
    NSMutableDictionary *bandLocks;	// 8 = 0x8
}

+ (id)systemSpectrumManager;	// IMP=0x000000000000504a
- (id)lockForBand:(int)arg1;	// IMP=0x0000000000005130
- (void)dealloc;	// IMP=0x00000000000050e6
- (id)init;	// IMP=0x0000000000005086

@end

