//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "D2DInquiryDelegate.h"
#import "D2DPairingDelegate.h"

@class NSBox, NSButton, NSProgressIndicator, NSTextField, NSViewController;

@interface D2DWindow : NSWindowController <D2DInquiryDelegate, D2DPairingDelegate>
{
    NSBox *box;	// 80 = 0x50
    NSProgressIndicator *progress;	// 88 = 0x58
    NSTextField *status;	// 96 = 0x60
    NSButton *forward;	// 104 = 0x68
    NSButton *backward;	// 112 = 0x70
    NSButton *alternate;	// 120 = 0x78
    NSViewController *deviceView;	// 128 = 0x80
}

+ (id)deviceAuthorizeWindow:(id)arg1;	// IMP=0x00000000000087e4
+ (id)deviceInspectorWindow:(id)arg1;	// IMP=0x0000000000008745
+ (id)pairingWindowForDevice:(id)arg1;	// IMP=0x00000000000086bc
+ (id)deviceWindowWithView:(id)arg1 title:(id)arg2;	// IMP=0x00000000000085b0
@property(retain) NSViewController *deviceView; // @synthesize deviceView;
@property NSButton *alternate; // @synthesize alternate;
@property NSButton *backward; // @synthesize backward;
@property NSButton *forward; // @synthesize forward;
@property NSTextField *status; // @synthesize status;
@property NSProgressIndicator *progress; // @synthesize progress;
@property NSBox *box; // @synthesize box;
- (void)pairingComplete:(id)arg1 error:(id)arg2;	// IMP=0x00000000000091b4
- (void)pairingUserPasskeyNotification:(id)arg1 passkey:(unsigned long long)arg2;	// IMP=0x0000000000009117
- (void)pairingUserConfirmationRequest:(id)arg1 numericValue:(unsigned long long)arg2;	// IMP=0x000000000000907a
- (void)pairingPINCodeRequest:(id)arg1;	// IMP=0x0000000000008fe5
- (void)pairingConnecting:(id)arg1;	// IMP=0x0000000000008f50
- (void)pairingStarted:(id)arg1;	// IMP=0x0000000000008ebb
- (void)inquiryComplete:(id)arg1 error:(id)arg2;	// IMP=0x0000000000008d54
- (void)inquiry:(id)arg1 deviceNameUpdated:(id)arg2 devicesRemaining:(unsigned long long)arg3;	// IMP=0x0000000000008c84
- (void)inquiry:(id)arg1 startedUpdatingDeviceNames:(unsigned long long)arg2;	// IMP=0x0000000000008bda
- (void)inquiry:(id)arg1 foundDevice:(id)arg2;	// IMP=0x0000000000008b1b
- (void)inquiryStarted:(id)arg1;	// IMP=0x0000000000008a3f
- (void)onAlternateClick:(id)arg1;	// IMP=0x0000000000008a29
- (void)onBackwardClick:(id)arg1;	// IMP=0x00000000000089f9
- (void)onForwardClick:(id)arg1;	// IMP=0x00000000000089c9
- (void)contract:(id)arg1;	// IMP=0x00000000000088f6
- (void)expand:(id)arg1;	// IMP=0x0000000000008827

@end

