//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FauxUIElement_tmp : NSObject
{
    NSString *role;	// 8 = 0x8
    id parent;	// 16 = 0x10
}

+ (id)elementWithRole:(id)arg1 parent:(id)arg2;	// IMP=0x000000000000166f
- (id)accessibilityFocusedUIElement;	// IMP=0x0000000000001c64
- (id)accessibilityHitTest:(struct CGPoint)arg1;	// IMP=0x0000000000001c5a
- (BOOL)accessibilityIsIgnored;	// IMP=0x0000000000001c52
- (void)accessibilityPerformAction:(id)arg1;	// IMP=0x0000000000001c4c
- (id)accessibilityActionDescription:(id)arg1;	// IMP=0x0000000000001c44
- (id)accessibilityActionNames;	// IMP=0x0000000000001c2b
- (void)accessibilitySetValue:(id)arg1 forAttribute:(id)arg2;	// IMP=0x0000000000001bd9
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;	// IMP=0x0000000000001b86
- (id)accessibilityAttributeValue:(id)arg1;	// IMP=0x00000000000018e2
- (id)accessibilityAttributeNames;	// IMP=0x00000000000017ed
- (unsigned long long)hash;	// IMP=0x00000000000017a0
- (BOOL)isEqual:(id)arg1;	// IMP=0x000000000000171b
- (void)dealloc;	// IMP=0x00000000000016b6
- (id)initWithRole:(id)arg1 parent:(id)arg2;	// IMP=0x00000000000015e0
- (id)locString:(id)arg1;	// IMP=0x0000000000001580

@end

