//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSFormatter.h"

@interface HIDNameFormatter : NSFormatter
{
    int _maxLength;	// 8 = 0x8
}

+ (id)maxLengthFormatter:(int)arg1;	// IMP=0x0000000000019370
- (BOOL)isPartialStringValid:(id)arg1 newEditingString:(id *)arg2 errorDescription:(id *)arg3;	// IMP=0x000000000001947a
- (BOOL)getObjectValue:(id *)arg1 forString:(id)arg2 errorDescription:(id *)arg3;	// IMP=0x0000000000019464
- (id)stringForObjectValue:(id)arg1;	// IMP=0x0000000000019424
- (void)dealloc;	// IMP=0x00000000000193f7
- (id)initWithMaxLength:(int)arg1;	// IMP=0x00000000000193b7

@end

