//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IOBluetoothDevicePair.h"

#import "D2DPairing.h"

@class D2DPeer;

@interface IOBluetoothDevicePair (IOBluetoothProtocol) <D2DPairing>
+ (id)pairingWithDevice:(id)arg1;	// IMP=0x00000000000078b4
- (void)deviceSimplePairingComplete:(id)arg1 status:(unsigned char)arg2;	// IMP=0x0000000000007e7d
- (void)devicePairingFinished:(id)arg1 error:(int)arg2;	// IMP=0x0000000000007d9c
- (void)devicePairingUserPasskeyNotification:(id)arg1 passkey:(unsigned int)arg2;	// IMP=0x0000000000007d15
- (void)devicePairingKeypressNotification:(id)arg1 type:(unsigned long long)arg2;	// IMP=0x0000000000007c8e
- (void)devicePairingUserConfirmationRequest:(id)arg1 numericValue:(unsigned long long)arg2;	// IMP=0x0000000000007c07
- (void)devicePairingPINCodeRequest:(id)arg1;	// IMP=0x0000000000007b83
- (void)devicePairingConnecting:(id)arg1;	// IMP=0x0000000000007aff
- (void)devicePairingStarted:(id)arg1;	// IMP=0x0000000000007a7b
- (void)cancelPairing;	// IMP=0x0000000000007a49
- (void)replyUserAuthorized:(BOOL)arg1;	// IMP=0x0000000000007a37
- (void)replyPINData:(id)arg1;	// IMP=0x00000000000079e0
- (BOOL)startPairing:(id *)arg1;	// IMP=0x00000000000079ae
- (void)setPairingDevice:(id)arg1;	// IMP=0x000000000000799c
@property(readonly) D2DPeer *pairingDevice;
@property id pairingDelegate;
- (id)_startPairing;	// IMP=0x0000000000007875
@end

