//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextFieldCell.h"

@interface IOBluetoothAccessibilityIgnoredTextFieldCell_tmp : NSTextFieldCell
{
}

- (id)accessibilityHitTest:(struct CGPoint)arg1;	// IMP=0x0000000000017ee3
- (BOOL)accessibilityIsIgnored;	// IMP=0x0000000000017ed8

@end

