//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class IOBluetoothDevice, IOBluetoothDevicePair, IOBluetoothDevicePairViewControllerExpansion_tmp, IOBluetoothPasskeyDisplay_tmp, NSString;

@interface IOBluetoothDevicePairViewController_tmp : NSViewController
{
    id <IOBluetoothDevicePairDelegate> _delegate;	// 104 = 0x68
    IOBluetoothDevice *_device;	// 112 = 0x70
    IOBluetoothDevicePair *_devicePair;	// 120 = 0x78
    IOBluetoothPasskeyDisplay_tmp *_passkeyDisplay;	// 128 = 0x80
    BOOL _useCustomPINCode;	// 136 = 0x88
    NSString *_PINCode;	// 144 = 0x90
    IOBluetoothDevicePairViewControllerExpansion_tmp *_expansion;	// 152 = 0x98
}

@property NSString *PINCode; // @synthesize PINCode=_PINCode;
@property(retain) IOBluetoothPasskeyDisplay_tmp *passkeyDisplay; // @synthesize passkeyDisplay=_passkeyDisplay;
@property(retain) IOBluetoothDevicePair *devicePair; // @synthesize devicePair=_devicePair;
@property(retain) IOBluetoothDevice *device; // @synthesize device=_device;
@property __weak id <IOBluetoothDevicePairDelegate> delegate; // @synthesize delegate=_delegate;
- (void)devicePairingKeypressNotification:(id)arg1 type:(unsigned char)arg2;	// IMP=0x0000000000005b15
- (void)deviceSimplePairingComplete:(id)arg1 status:(unsigned char)arg2;	// IMP=0x0000000000005a9c
- (void)devicePairingFinished:(id)arg1 error:(int)arg2;	// IMP=0x00000000000059f0
- (void)devicePairingUserPasskeyNotification:(id)arg1 passkey:(unsigned int)arg2;	// IMP=0x0000000000005914
- (void)devicePairingUserConfirmationRequest:(id)arg1 numericValue:(unsigned int)arg2;	// IMP=0x000000000000581c
- (void)devicePairingPINCodeRequest:(id)arg1;	// IMP=0x00000000000054be
- (void)devicePairingConnecting:(id)arg1;	// IMP=0x0000000000005449
- (void)devicePairingStarted:(id)arg1;	// IMP=0x00000000000053d4
- (void)stop;	// IMP=0x00000000000053a6
- (int)pairWithDevice:(id)arg1;	// IMP=0x00000000000052b3
- (int)pairWithDevice:(id)arg1 usingPincode:(id)arg2;	// IMP=0x0000000000005237
- (void)loadView;	// IMP=0x00000000000051cc
- (void)cancelPairing;	// IMP=0x000000000000859e
- (id)pairingDevice;	// IMP=0x000000000000858c
- (void)setPairingDelegate:(id)arg1;	// IMP=0x00000000000084b5
- (id)pairingDelegate;	// IMP=0x0000000000008486
- (int)pairingWithDevice:(id)arg1 usingPincode:(id)arg2;	// IMP=0x0000000000008474
- (int)pairingWithDevice:(id)arg1;	// IMP=0x0000000000008462

@end

