//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "D2DProtocol.h"

@interface IOBluetoothProtocol : NSObject <D2DProtocol>
{
    BOOL supportsSSP;	// 8 = 0x8
}

+ (id)systemBluetoothProtocol;	// IMP=0x0000000000005d6e
@property BOOL supportsSSP; // @synthesize supportsSSP;
- (BOOL)unpairWithDevice:(id)arg1;	// IMP=0x000000000000661e
- (id)pairWithDevice:(id)arg1;	// IMP=0x0000000000006605
- (id)searchForDevicesWithAttribute:(struct IOBluetoothDeviceSearchAttributes *)arg1;	// IMP=0x000000000000658b
- (id)searchForDevicesOfType:(int)arg1;	// IMP=0x0000000000006511
- (id)connectedDevices;	// IMP=0x00000000000064f8
- (id)pairedDevices;	// IMP=0x00000000000061ea
- (BOOL)bluetoothPowerOff;	// IMP=0x00000000000061d4
- (id)protocolName;	// IMP=0x00000000000061c7
- (void)bluetoothPairedDevicesChanged:(id)arg1;	// IMP=0x000000000000617b
- (void)bluetoothDeviceNameChanged:(id)arg1;	// IMP=0x00000000000060b6
- (void)bluetoothUserNotification:(id)arg1 deviceDisconnected:(id)arg2;	// IMP=0x0000000000006001
- (void)bluetoothUserNotification:(id)arg1 deviceConnected:(id)arg2;	// IMP=0x0000000000005f16
- (void)bluetoothPowerOn:(id)arg1;	// IMP=0x0000000000005eea
- (void)bluetoothPowerOff:(id)arg1;	// IMP=0x0000000000005ebe
- (void)configureSSPSupport;	// IMP=0x0000000000005cb0

@end

