//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IOBluetoothDevice.h"

#import "D2DPeer.h"

@class D2DPersonality, NSData, NSDictionary, NSString, NSURL;

@interface IOBluetoothDevice (IOBluetoothProtocol) <D2DPeer>
+ (id)protocolName;	// IMP=0x000000000000665c
- (void)disconnectionComplete:(id)arg1 status:(int)arg2;	// IMP=0x00000000000072b4
- (void)connectionComplete:(id)arg1 status:(int)arg2;	// IMP=0x0000000000007272
- (void)remoteNameRequestComplete:(id)arg1 status:(int)arg2;	// IMP=0x000000000000726c
- (BOOL)isTrackpad;	// IMP=0x00000000000071d4
- (int)maxNameLength;	// IMP=0x0000000000007199
- (BOOL)tempDeviceHasServiceRecordWithUUID:(id)arg1;	// IMP=0x0000000000007041
- (void)disconnectDevice;	// IMP=0x0000000000006fa1
- (void)connectDevice;	// IMP=0x0000000000006ed2
@property(readonly) BOOL hasResolvedName;
@property(readonly) BOOL hasPairingOptions;
@property(readonly) float batteryPercent;
@property(readonly) BOOL isConnectable;
@property(readonly) unsigned int servicesConfigured;
@property(readonly) int sortingOrder;
@property(readonly) BOOL paired;
@property(readonly) BOOL connected;
@property(readonly) BOOL foundRSSI;
- (id)deviceBehaviours;	// IMP=0x00000000000068fe
- (id)deviceServices;	// IMP=0x00000000000068f6
@property(readonly) NSDictionary *deviceProperties;
@property(readonly) NSDictionary *devicePreferences;
@property id deviceDelegate;
@property(readonly) int deviceSubclass;
@property(readonly) int deviceClass;
@property(readonly) NSURL *deviceURL;
- (id)deviceIcon;	// IMP=0x000000000000679d
@property(readonly) NSData *deviceAddress;
@property(copy) NSString *deviceName;
@property(readonly) D2DPersonality *personality;
@end

