//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IOBluetoothDevice.h"

@interface IOBluetoothDevice (IOBluetoothDeviceImages)
+ (id)imageForSystemIconType:(unsigned int)arg1 ofSize:(struct CGSize)arg2;	// IMP=0x0000000000004f2f
- (id)image;	// IMP=0x0000000000004a33
- (id)loadImageFromBundle:(id)arg1 withResourceNamed:(id)arg2;	// IMP=0x0000000000004966
- (id)loadImageFromBundleID:(id)arg1 withResourceNamed:(id)arg2;	// IMP=0x00000000000048bc
@end

