//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSImage.h"

@interface NSImage (D2DKit)
+ (void)releaseImageCache;	// IMP=0x00000000000180a6
+ (void)removeNamedImageFromCache:(id)arg1;	// IMP=0x0000000000018060
+ (void)cacheNamedImage:(id)arg1;	// IMP=0x0000000000017f96
- (struct CGImage *)cgImage;	// IMP=0x00000000000180cd
@end

