//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (D2DKit)
+ (id)templateImageFromMyBundle:(id)arg1;	// IMP=0x0000000000016c56
+ (id)cachedImageFromMyBundle:(id)arg1;	// IMP=0x0000000000016bf0
+ (id)namedImageFromMyBundle:(id)arg1;	// IMP=0x0000000000016ad2
- (id)templateImageFromMyBundle:(id)arg1;	// IMP=0x0000000000016c8b
- (id)cachedImageFromMyBundle:(id)arg1;	// IMP=0x0000000000016c27
- (id)namedImageFromMyBundle:(id)arg1;	// IMP=0x0000000000016bc1
@end

